### ISSUE TITLE
Various github project issue shortlinks

### ISSUE THREAD

**Issue by riking** [dlowe-net/linksnip#12]
https://github.com/golang/go/issues/12345 -> https://go.dev/issues/12345

https://github.com/kubernetes/kubernetes/issues/$1 -> https://issues.k8s.io/12345 -- also https://github.com/kubernetes/features/issues/$1 https://github.com/kubernetes/enhancements/issues/$1

https://github.com/kubernetes/k8s.io/blob/main/apps/k8s-io/configmap-nginx.yaml#L249

https://dolp.in/ https://dolp.in/i12345

**Comment by dlowe-net** [comment]
https://github.com/kubernetes/k8s.io/blob/main/dns/zone-configs/k8s.io._0_base.yaml has a bunch of kubernetes shorter vanity domains.

**Comment by riking** [comment]
Looks like only the redirect.kubernetes.io domains are covered in the file I linked

**Comment by dlowe-net** [comment]
Could you add test cases for these in `PopupSpec.js`? Github should run them if they're added.
