### ISSUE TITLE
Amazon links now broken by linksnip shortening

### ISSUE THREAD

**Issue by ekovac** [dlowe-net/linksnip#7]
Steps to reproduce:
1. Navigate to an amazon product page (for example: https://www.amazon.com/gp/product/B008200LHW/)
2. Click linksnip button
3. Open a new tab
4. Paste the result (https://amzn.com/B008200LHW) in nav bar and hit enter

Expected behavior:
Link works

Actual behavior:
It doesn't.

I assume this is the result of a change on the Amazon side of things, or possibly even an outage on their side? Figured I'd report it nonetheless.

**Comment by dlowe-net** [comment]
They may very well be shutting it down. I notice that sharing an item via email no longer gives the shortlink, where I'm pretty sure it used to be. They were titled "Permalinks" so one would hope that this isn't the case.

I'm going to wait on this until I get confirmation either way. If it really is being turned down, Linksnip can still be useful for removing all the url cruft.

**Comment by dlowe-net** [comment]
Amusingly, https://www.amzn.com/B008200LHW still works. I think they just broke it.

**Comment by dlowe-net** [comment]
Addressed by c43c2b7c88379cdb193ae7b33de80becb15f3cf8 on the observation that https://amzn.com/dp/B008200LHW  works, too.
